var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                               !!                               ",
   "                                                                  xxx           ",
   "                                                   xx   y  xx    xx!!xx         ",
   "                 o                   o o      xx xx  xx           x!!!x         ",
   "                   xxx                     ! x         xxxx       xx!xx         ",
   "            xxx y                 y   xxxxx!  x                    xvx          ",
   "      xxx               xx                                                  xx  ",
   "  xx               !!!           xxx            o o                          x  ",
   "  x  xxx  xxx  y         o          !!!!                        y            x  ",
   "  x                                      xxx!!!xx     y                    o x  ",
   "  x          xxxx       o       y                        xxxx                x  ",
   "  x  @       x  x !!!!xx             xxx                       y      xxxxxxxx  ",
   "  xxxxxxx!!xxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxx     xxxxx   xxxxxxxxxxxxx        ",
   "        x!!x                  x!!!x          x!!!!!x   x     x                  ",
   "        xxxx                  x!!!x          x!!!!!x   x!!!!!x                  ",
   "                              x!!!x          x!!!!!x   x!!!!!x                  ",
   "                              xxxxx          xxxxxxx   xxxxxxx                  ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx!!!!!!!  yxx                                 x!x  ",
   "                                      xx!!!!!!!!!!xx         xx !!!!!!!!!    xx                              x!x  ",
   "                                       xxxxxxxxxx!!x        xxxx                                  o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                            y                     x!x         x                            xxxxxxxxxxxxxxx!!!!!x  ",
   "                           y                     xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                          y     xxxxxxx                              xx  |   |   |  xx     xxxxxxxxxxxxxxxxxxxxx  ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                         xxxx!!!!!                             xxxx!!!!!xxxx                                      ",
   "                              xx!!!                 x     x            xxxxxxx        xxx         xxx             ",
   "                     xxxxx      x        y               x     x                           xx  xxx       x x      ",
   "                                x                   x                             x         x                     ",
   "                    x           x                   x                            xx         x                     ",
   "                    x               y            xx    x                             x         x                  ",
   "                    x      y                    x     x      o  o     x!!x         x    !!!     x                 ",
   "               xx!!!xx        xxx   xxx        x     x                x   x        x       xx                     ",
   "              xxx!!!x    xx         x   x      y    x     x     xxxxxx    x   x   xxxxxxxxx       x               ",
   "             xx x!!!x    xx  !!!!!  x o x          x    xx                x!x!!  x               x                ",
   "     @       x  x!!!x    x        x   x          x     x             xx   x    x               x                  ",
   "    xxx      x   xxx      x        x   x   xxxx       x     x        !!!!x       x   xxxxx   xxxxxx      x  y     ",
   "    x x      x         x       xx o xx   !!!!! x     x     xxxxx          x     o     x x         x               ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x            xxx     ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx        y xxx       ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx             x       ",
   "!!!!x x!!!!!!x         x!!!!!x                  y   xx!!!!!!xx  !                     xxxxxxx xxxxxx!!!!!!xxxxxxx ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                  x!!!!!!x        ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                  xxxxxxxx        ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                xx                     xxx xxx              x          x                                      ",
   "               x                       x   x                x   oooo   x       xxx                            ",
   "       xxxxxx!!!!!!!!!!        y      x   x      y          x          x      x!!!x                           ",
   "    xx                 xxxxxx               xx   x          xxxxxxxxxxxx       xxx                            ",
   "      xxxxx                   !!!!xx!xx   xx!!!!!!x   xxx!!!xx                                                ",
   "           xxxxxxxxx                  x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                     xxxx             x  xx           x                    x!!!x                              ",
   "                         !x           x   x           x                     xxx                               ",
   "                          xxxx       xx   xx          x                                                       ",
   "     xxxxxxx    y             xx      x   x= = = =    x            xxx                                        ",
   "            x                         x   x           x           x!!!x                                       ",
   "             xx   xxx!!!!!!xxxx       x   x    = = = =x     o      xxx       xxx                              ",
   "            xxxx    x!!!!!!x         xx   xx          x                     x!!!x                             ",
   "           xxxxxx   x!!! xx    o   o  x   x           x     x                xxv        xxx                   ",
   "          xxxxxxxx  xxxxx             x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                            xx xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "       xxxxx                 x !!!!!       x     xxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x    xxxxx                                x!!!x                xxx  ",
   "  x x                         x    xxx    x        x                                  xxx                x x  ",
   "  x                           x !  xxx    xxxxxxx  xxxxxxx                  xxxxx                          x  ",
   "  x      xxxxxxxx             x !          x     x                       x   x                             x  ",
   "  x               xxxx       xx                  x                      x  y x                             x  ",
   "  x             y      xxxx                x       |xxxx|    |xxxx|    xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x             xxxxxx xx    xx        xxx               y              xxx       x!!!x          x         x  ",
   "  x       xxxx    oxxxo       x    xxx!!!!x                             x x        xxx          xxx        x  ",
   "  x    xx          xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @    x!!xxxx         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                   y                                                              ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
